---
- name: Install Node and pm2
  hosts: cents
  gather_facts: no
  vars:
    NODEJS_VERSION: "12"

  tasks:
    - name: Update all packages - Always take a few seconds
      yum: name='*' state=latest
    
    - name: Install nvm - After curl
      shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.35.2/install.sh | bash
       
    - name: Reload bash
      shell: . /root/.bashrc
     
    - name: Install node by nvm
      shell: source /root/.nvm/nvm.sh && nvm install node
       
    - name: Install pm2
      shell: npm i -g pm2
