---
- name: Install Node and pm2
  hosts: cents
  accelerate: true
  gather_facts: no

  tasks:
    - name: upgrade all packages
      yum: name='*' state=latest
    
    - name: Install nvm
      shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.35.2/install.sh | bash
       
    - name: reload bash
      shell: source ~/.bashrc
     
    - name: Install node by nvm
      shell: nvm install node
       
    - name: Install pm2
      shell: npm i -g pm2
