---
- name: Copy Files and Config Apache
  hosts: cents
  gather_facts: no
  vars:
    server: 10.0.0.190
    sshpass: le153183
    serverdir: /var/www/Pj_Checker
    nodedir: /var/www
    apconf: /etc/httpd/conf/httpd.conf
    phpconf: /etc/php.ini
    html: /var/www/html

  tasks:
    - name: install rsync
      yum: name=rsync state=present
    
    - name: install sshpass
      yum: name=sshpass state=present

    - name: add known hosts
      shell: ssh-keyscan -H 10.0.0.190 > ~/.ssh/known_hosts

    - name: copy sync
      shell: sshpass -p "le153183" rsync -avzh root@10.0.0.190:/var/www/Pj_Checker /var/www

    - name: Replace Root Directory
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: /var/www/html
        replace: /var/www/Pj_Checker

    - name: PHP enable
      replace:
        path: /etc/php.ini
        regexp: short_open_tag = Off
        replace: short_open_tag = On

    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted