---
- name: Copy Files and Config Apache
  hosts: cents
  accelerate: true
  gather_facts: no

  tasks:
    - name: Copy source Directory
      synchronize:
        mode: push
        src: /var/www/Pj_Checker
        dest: /var/www/Pj_Checker

    - name: Replace Root Directory
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: /var/www/html
        replace: /var/www/Pj_Checker

    - name: PHP enable
      replace:
        path: /etc/php.ini
        regexp: short_open_tag = Off
        replace: short_open_tag = On

    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted
