---
- name: Copy Files and Config Apache
  hosts: cents
  gather_facts: no

  tasks:
    - name: Install python 3 to use synchromize
      yum: name=python3 state=present
    
    - name: install the latest version of rsync
      yum:
        name: rsync
        state: latest

    - name: Copy source Directory - push
      synchronize:
        mode: push
        src: /var/www/Pj_Checker
        dest: /var/www/Pj_Checker
        rsync_opts: "{{sync_rsync_opts|default(omit)}}"
      delegate_to: "{{inventory_hostname}}"

    - name: Replace Root Directory
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: /var/www/html
        replace: /var/www/Pj_Checker

    - name: PHP enable
      replace:
        path: /etc/php.ini
        regexp: short_open_tag = Off
        replace: short_open_tag = On

    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted
