---
- name: Copy Files and Config Apache
  hosts: cents
  gather_facts: no

  tasks:
    - name: Install python 3 to use synchromize
      yum: name=python3 state=present
    
    - name: install rsync
      yum: name=rsync state=present
    
    - name: install sshpass
      yum: name=sshpass state=present

    - name: copy sync
      shell: sshpass -p "le153183" rsync -avzh root@10.0.0.190:/var/www/Pj_Checker /var/www

    - name: Replace Root Directory
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: /var/www/html
        replace: /var/www/Pj_Checker

    - name: PHP enable
      replace:
        path: /etc/php.ini
        regexp: short_open_tag = Off
        replace: short_open_tag = On

    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted
