---
- name: Copy Files and Config Apache
  hosts: cents
  gather_facts: no

  tasks:
    # - name: Copy directory
    #   copy: name=httpd state=present

    - name: Replace Root Directory
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: /var/www/html
        replace: /var/www/Pj_Checker

    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted
    
      