---
- name: Copy Files and Config Apache
  hosts: cents
  gather_facts: no

  tasks:
    - name: Copy directory
      copy: name=httpd state=present

    - name: Apache, directory Link
      yum: name=httpd state=present