---
- name: Start and startup AM and Firewalld setting
  hosts: cents
  gather_facts: no
  vars:
    httport: 80

  tasks:
    - name: start apache web server
      service: name=httpd state=started

    - name: Register Startup mariadb
      shell: systemctl enable mariadb

    - name: Register Startup apache
      shell: systemctl enable httpd

    - name: start mariadb
      service: name=mariadb state=started

    - name: start firewall
      shell: systemctl start firewalld

    - name: enable ports
      shell: firewall-cmd --permanent --zone=public --add-port={{ httport }}/tcp

    - name: reload firewall
      shell: firewall-cmd --reload
