---
- name: Start and startup AM
  hosts: cents
  gather_facts: no

  tasks:
    - name: start apache web server
      service: name=httpd state=started

    - name: Register Startup mariadb
      shell: systemctl enable mariadb

    - name: Register Startup apache
      shell: systemctl enable httpd

    - name: start mariadb
      service: name=mariadb state=started

    - name: disable firewall
      shell: systemctl stop firewalld

    - name: enable ports
      shell: []