---
- name: 6. Start pm2 and Register Startup
  hosts: delab
  gather_facts: no
  vars:
    pm2port: 58022
    pm2name: nassvr_code42_1
    mntdir: /mnt/nas/smms_output

  tasks:
    - name: pm2 try serve catch restart
      shell: pm2 serve {{ mntdir }} {{ pm2port }} --force --name "{{ pm2name }}" || pm2 restart {{ pm2name }}

    - name: pm2 startup
      shell: pm2 startup

    - name: pm2 save
      shell: pm2 save
