---
  - name: makedb
    hosts: delab1
    gather_facts: no
    vars:
      dbname: delab_test
      sqlpath: /var/www/Pj_Checker/Ansible/test.sql
  
    tasks:
      - name: Create a new database with name {{dbname}}
        mysql_db:
          name: "{{dbname}}"
          state: present

      - name: sql
        mysql_db:
          name: delab_test
          state: import
          target: /var/www/Pj_Checker/Ansible/test.sql