---
  - name: remount
    hosts: delab1
    gather_facts: no
    vars:
      # nasdir : In /etc/ansible/host
      mntdir: /mnt/nas/smms_output
      nasuser: Stryx
      naspass: emfRoskfk!23
  
    tasks:
      - name: Unmount drive
        shell: umount {{mntdir}} -lf || echo

      - name: Mount drive
        shell: mount -t cifs {{nasdir}} {{mntdir}} -o user={{nasuser}},pass='{{naspass}}',rw,vers=1.0,context=system_u:object_r:httpd_sys_content_t:s0

      - name: make mount script
        shell: |
          echo "#!/bin/sh
          # chkconfig: 234 90 90
          # description: mount nas drive
          mount -t cifs {{nasdir}} {{mntdir}} -o user={{nasuser}},pass='{{naspass}}',rw,vers=1.0,context=system_u:object_r:httpd_sys_content_t:s0 || echo "mounted"
          " > /etc/init.d/mount

      - name: make it startup
        shell: |
          chmod 755 /etc/init.d/mount
          chwon root.root /etc/init.d/mount
          chkconfig --add mount

          